### ISSUE TITLE
Remove PyMC requirement?

### ISSUE THREAD

**Issue by maresb** [conda-forge/nutpie-feedstock#29]
### Comment:

Since Nutpie can be used with either PyMC or Stan, would it make sense to remove the PyMC, PyTensor and Numba dependencies? (If we still need version pins, we could use `run_constrained` which means "optional, but if installed, then pin to some version specification".)

Note: In case we remove Numba then we'd probably need to update the instructions in the Nutpie readme to install Numba alongside Nutpie when using with PyMC.

**Comment by aseyboldt** [comment]
I think that makes sense.

> (If we still need version pins, we could use run_constrained which means "optional, but if installed, then pin to some version specification".)

I didn't know this was a thing, sounds good to me.
